steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "CI-Trigger wurde erfolgreich durch einen Push auf den Main-Branch ausgelöst!"
        echo "Überprüfe den Inhalt des 'proto'-Verzeichnisses:"
        ls -l proto/

# Hinzufügen der Logging-Konfiguration, um den Fehler zu beheben
options:
  logging: CLOUD_LOGGING_ONLY