# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kiorga/datamodel/task.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'kiorga/datamodel/task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bkiorga/datamodel/task.proto\x12\x10kiorga.datamodel\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x05\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12,\n\x06status\x18\x04 \x01(\x0e\x32\x1c.kiorga.datamodel.TaskStatus\x12\x30\n\x08priority\x18\x05 \x01(\x0e\x32\x1e.kiorga.datamodel.TaskPriority\x12\x1c\n\x14\x61ssigned_to_agent_id\x18\x06 \x01(\t\x12\x18\n\x10\x63reator_agent_id\x18\x07 \x01(\t\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0c\x64\x65pendencies\x18\n \x03(\t\x12N\n\x15input_data_references\x18\x0b \x03(\x0b\x32/.kiorga.datamodel.Task.InputDataReferencesEntry\x12P\n\x16output_data_references\x18\x0c \x03(\x0b\x32\x30.kiorga.datamodel.Task.OutputDataReferencesEntry\x12 \n\x18success_criteria_metrics\x18\r \x01(\t\x12\x16\n\x0eparent_task_id\x18\x0e \x01(\t\x12,\n\x08\x64ue_date\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rco_pilot_mode\x18\x10 \x01(\x08\x1a:\n\x18InputDataReferencesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a;\n\x19OutputDataReferencesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\x92\x01\n\nTaskStatus\x12\x1b\n\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13TASK_STATUS_PENDING\x10\x01\x12\x1b\n\x17TASK_STATUS_IN_PROGRESS\x10\x02\x12\x19\n\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n\x12TASK_STATUS_FAILED\x10\x04*\xac\x01\n\x0cTaskPriority\x12\x1d\n\x19TASK_PRIORITY_UNSPECIFIED\x10\x00\x12\x18\n\x14TASK_PRIORITY_URGENT\x10\x01\x12\x16\n\x12TASK_PRIORITY_HIGH\x10\x02\x12\x18\n\x14TASK_PRIORITY_MEDIUM\x10\x03\x12\x15\n\x11TASK_PRIORITY_LOW\x10\x04\x12\x1a\n\x16TASK_PRIORITY_OPTIONAL\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kiorga.datamodel.task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK_INPUTDATAREFERENCESENTRY']._loaded_options = None
  _globals['_TASK_INPUTDATAREFERENCESENTRY']._serialized_options = b'8\001'
  _globals['_TASK_OUTPUTDATAREFERENCESENTRY']._loaded_options = None
  _globals['_TASK_OUTPUTDATAREFERENCESENTRY']._serialized_options = b'8\001'
  _globals['_TASKSTATUS']._serialized_start=825
  _globals['_TASKSTATUS']._serialized_end=971
  _globals['_TASKPRIORITY']._serialized_start=974
  _globals['_TASKPRIORITY']._serialized_end=1146
  _globals['_TASK']._serialized_start=83
  _globals['_TASK']._serialized_end=822
  _globals['_TASK_INPUTDATAREFERENCESENTRY']._serialized_start=703
  _globals['_TASK_INPUTDATAREFERENCESENTRY']._serialized_end=761
  _globals['_TASK_OUTPUTDATAREFERENCESENTRY']._serialized_start=763
  _globals['_TASK_OUTPUTDATAREFERENCESENTRY']._serialized_end=822
# @@protoc_insertion_point(module_scope)
